Repository AY2324S2-CS2113-W13-2/tp, pull requests merged in 2024-04, with the labels that each got.

#111 Fixed adding of tasks in week view
  src/main/java/data/TaskManager.java
  src/main/java/time/MonthView.java
  src/main/java/time/View.java
  text-ui-test/input.txt
Labels: priority.High

#115 Ug branch
  .gitignore
  docs/UserGuide.md
  docs/images/Deadline-Example.png
  docs/images/Event-Example.png
  docs/images/Todo-Example.png
  src/main/java/data/TaskManager.java
  src/main/java/data/TaskType.java
  src/main/java/data/Todo.java
  src/main/java/seedu/duke/Main.java
  src/test/java/data/TaskManagerExceptionTest.java
  src/test/java/data/TaskManagerTest.java
Labels: priority.High

#119 Final checkstyle and documentation cleanup
  src/main/java/data/Deadline.java
  src/main/java/data/Event.java
  src/main/java/data/TaskManager.java
  src/main/java/data/TaskManagerException.java
  src/main/java/data/Todo.java
  src/main/java/storage/Storage.java
  src/main/java/time/DateUtils.java
Labels: priority.High

#139 Change Monthview display to shorthand
  docs/UserGuide.md
  src/main/java/seedu/duke/Main.java
  src/main/java/time/MonthView.java
  src/main/java/ui/UiRenderer.java
Labels: priority.Medium

#140 Fix PED bugs
  src/main/java/data/MarkTaskException.java
  src/main/java/data/SetPriorityException.java
  src/main/java/data/TaskManager.java
  src/main/java/storage/Storage.java
  src/main/java/ui/AvatarUi.java
Labels: severity.Medium

#142 Improve UG formatting and fix documentation errors from PE-D
  build.gradle
  docs/UserGuide.md
  docs/diagrams/class/Data.puml
  docs/images/Month-To-Week-View-After-Example.png
  docs/images/MonthView-Next-After-Example.png
  docs/images/MonthView-Next-Before-Example.png
  docs/images/Week-To-Month-View-After-Example.png
  docs/images/Week-To-Month-View-Before-Example.png
  docs/images/WeekView-Next-After-Example.png
  docs/images/WeekView-Next-Before-Example.png
Labels: priority.Medium

#148 Added exception handling for date parsing and storage and refactoring of taskManager methods
  build.gradle
  docs/team/kyhjonathan.md
  src/main/java/data/Event.java
  src/main/java/data/TaskManager.java
  src/main/java/data/Todo.java
  src/main/java/data/exceptions/MarkTaskException.java
  src/main/java/data/exceptions/SetPriorityException.java
  src/main/java/data/exceptions/StorageFileException.java
  src/main/java/data/exceptions/TaskManagerException.java
  src/main/java/seedu/duke/Main.java
  src/main/java/storage/Storage.java
  src/main/java/storage/StorageFileException.java
  src/test/java/data/TaskManagerExceptionTest.java
  src/test/java/data/TaskManagerTest.java
Labels: priority.Medium

#147 Add Command and Parser classes
  src/main/java/commandparser/CommandHandler.java
  src/main/java/commandparser/StringParser.java
  src/main/java/seedu/duke/Main.java
  src/main/java/time/MonthView.java
  src/main/java/time/View.java
  src/main/java/time/WeekView.java
  src/main/java/ui/UiRenderer.java
Labels: type.Task, priority.Medium

#155 Fix add in Week and MonthView, Add JUnit tests
  src/main/java/commandparser/CommandHandler.java
  src/main/java/commandparser/StringParser.java
  src/main/java/data/TaskManager.java
  src/main/java/time/MonthView.java
  src/main/java/time/View.java
  src/main/java/time/WeekView.java
  src/test/java/commandparser/StringParserTest.java
  src/test/java/data/TaskManagerExceptionTest.java
  src/test/java/ui/MonthViewTest.java
  src/test/java/ui/WeekViewTest.java
Labels: type.Bug, priority.High, severity.High

#157 Add in Javadocs and JUnit testing
  docs/UserGuide.md
  src/main/java/commandparser/CommandHandler.java
  src/main/java/data/Event.java
  src/main/java/data/TaskManager.java
  src/main/java/data/exceptions/TaskManagerException.java
  src/main/java/seedu/duke/Main.java
  src/main/java/storage/Storage.java
  src/test/java/data/TaskManagerExceptionTest.java
  unused/icshandler/IcsHandler.java
  unused/icshandler/icstest.ics
Labels: priority.Medium

#159 Add exception and logging section to DG and move unused code to the appropriate folder
  docs/DeveloperGuide.md
  docs/diagrams/class/Exceptions.puml
  docs/images/class/Exceptions.png
  src/main/java/data/exceptions/TaskManagerException.java
  src/test/java/data/TaskManagerExceptionTest.java
  unused/data/exceptions/TaskManagerException.java
Labels: priority.Medium

#190 Amendments to DG and more test cases
  .gitignore
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/architecture/architeturediagram.png
  docs/diagrams/class/Storage.puml
  docs/diagrams/sequence/AddManagerSequenceDiagram.puml
  docs/diagrams/sequence/SaveAndLoadSequenceDiagrams.puml
  docs/images/After-Deletion-Week-View.png
  docs/images/AfterMarkingTaskWeekView.png
  docs/images/AfterSetPriorityWeekView.png
  docs/images/Before-Deletion-Week_View.png
  docs/images/BeforeMarkTaskWeekView.png
  docs/images/BeforeSetPriorityWeekView.png
  docs/images/QuitApplication.png
  docs/images/class/StorageClassDiagram.png
  docs/images/sequence/AddManagerSequenceDiagram.png
  docs/images/sequence/SaveAndLoadSequenceDiagram.png
  docs/team/kyhjonathan.md
  src/main/java/commandparser/CommandHandler.java
  src/main/java/commandparser/StringParser.java
  src/main/java/data/Deadline.java
  src/main/java/data/MarkTaskException.java
  src/main/java/data/SetPriorityException.java
  src/main/java/data/StorageFileException.java
  src/main/java/data/TaskManager.java
  src/main/java/data/TaskManagerException.java
  src/main/java/seedu/duke/Main.java
  src/main/java/storage/Storage.java
  src/main/java/time/View.java
  src/test/java/commandparser/StringParserTest.java
  src/test/java/data/TaskManagerTest.java
  src/test/java/data/exceptions/MarkTaskExceptionTest.java
  src/test/java/data/exceptions/SetPriorityExceptionTest.java
  src/test/java/data/exceptions/StorageFileExceptionTest.java
  src/test/java/data/exceptions/TaskManagerExceptionTest.java
  src/test/java/storage/StorageTest.java
  src/test/java/ui/UiRendererTest.java
Labels: priority.High
